"""auto update

Revision ID: 6ca8b50ad0a2
Revises: 
Create Date: 2026-08-12 05:47:35.976391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca8b50ad0a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('context_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.String(), nullable=False),
    sa.Column('location_summary', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_accuracy', sa.Float(), nullable=True),
    sa.Column('victim_count', sa.Integer(), nullable=False),
    sa.Column('triage_summary', sa.String(), nullable=True),
    sa.Column('hazards', sa.String(), nullable=True),
    sa.Column('kit_items', sa.String(), nullable=True),
    sa.Column('procedure_id', sa.String(), nullable=True),
    sa.Column('interventions', sa.String(), nullable=True),
    sa.Column('includes_health_data', sa.Boolean(), nullable=True),
    sa.Column('called_112', sa.String(), nullable=False),
    sa.Column('brief_text', sa.String(), nullable=True),
    sa.Column('content_pack_version', sa.String(), nullable=True),
    sa.Column('retention_choice', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_records_id'), 'incident_records', ['id'], unique=False)
    op.create_index(op.f('ix_incident_records_procedure_id'), 'incident_records', ['procedure_id'], unique=False)
    op.create_table('registered_kits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kit_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('location_note', sa.String(), nullable=True),
    sa.Column('contents', sa.String(), nullable=True),
    sa.Column('missing_items', sa.String(), nullable=True),
    sa.Column('last_checked', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registered_kits_id'), 'registered_kits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registered_kits_id'), table_name='registered_kits')
    op.drop_table('registered_kits')
    op.drop_index(op.f('ix_incident_records_procedure_id'), table_name='incident_records')
    op.drop_index(op.f('ix_incident_records_id'), table_name='incident_records')
    op.drop_table('incident_records')
    # ### end Alembic commands ###