"""add join_code to incident_sessions

Revision ID: e6ade0af58d8
Revises: acfce1488a4b
Create Date: 2026-08-19 14:59:26.590706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ade0af58d8'
down_revision: Union[str, Sequence[str], None] = 'acfce1488a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_sessions', sa.Column('join_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_incident_sessions_join_code'), 'incident_sessions', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_sessions_join_code'), table_name='incident_sessions')
    op.drop_column('incident_sessions', 'join_code')
    # ### end Alembic commands ###